services:
  ollama:
    build: ./ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    healthcheck:
      test:
        [
          "CMD",
          "sh",
          "-c",
          "curl -s http://localhost:11434/api/tags | grep -q 'mistral'",
        ]
      interval: 20s
      timeout: 5s
      retries: 30
      start_period: 120s

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_API_URL=http://ollama:11434
    depends_on:
      ollama:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  ollama-data:
    driver: local
