version: "3.8"

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: always
    entrypoint:
      [
        "/bin/sh",
        "-c",
        "ollama pull mistral && ollama pull llama3 && ollama serve",
      ]

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_API_URL=http://ollama:11434
    depends_on:
      - ollama
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always

volumes:
  ollama-data:
    driver: local
