services:
  ollama:
    build: ./ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    healthcheck:
      test:
        [
          "CMD",
          "sh",
          "-c",
          "curl -s http://localhost:11434/api/tags | grep -q 'mistral'",
        ]
      interval: 20s
      timeout: 5s
      retries: 30
      start_period: 120s

  backend:
    build: ./backend
    container_name: backend
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
        - action: rebuild
          path: ./backend/requirements.txt
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_API_URL=http://ollama:11434
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=app-db
      - DB_HOST=db
      - DB_PORT=5432
      - API_KEY=${API_KEY}
      - TEMPERATURE=0.7
      - MAX_TOKENS=2048
      - ASYNC_REQUEST=false
      - MAX_RETRIES=3
    depends_on:
      ollama:
        condition: service_healthy
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app-db
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Mount the schema script
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d app-db"]
      interval: 20s
      timeout: 5s
      retries: 30
      start_period: 20s

volumes:
  ollama-data:
    driver: local
  db-data:
    driver: local
