services:
  backend:
    build: ./backend
    container_name: backend
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
        - action: rebuild
          path: ./backend/requirements.txt
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_API_URL=http://host.docker.internal:11434
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=app-db
      - DB_HOST=db
      - DB_PORT=5432
      - API_KEY=${API_KEY}
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app-db
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d app-db"]
      interval: 20s
      timeout: 5s
      retries: 30
      start_period: 20s

volumes:
  ollama-data:
    driver: local
  db-data:
    driver: local
